# World systems phases organize when certain systems should run

TIME_UPDATE_PHASE = 999
TOWN_SYSTEMS_PHASE = 800
CHARACTER_UPDATE_PHASE = 500
CHARACTER_ACTION_PHASE = 499
BUILDING_UPDATE_PHASE = 400
BUSINESS_UPDATE_PHASE = 300
CLEAN_UP_PHASE = 100
