# World systems phases organize when certain systems should run

TIME_UPDATE_PHASE = 0
TOWN_SYSTEMS_PHASE = -100
CHARACTER_UPDATE_PHASE = -200
CHARACTER_ACTION_PHASE = -200
BUILDING_UPDATE_PHASE = -300
BUSINESS_UPDATE_PHASE = -400
CLEAN_UP_PHASE = -1000
