import logging
from typing import Any

import neighborly.plugins.talktown.business_archetypes as tot_businesses
import neighborly.plugins.talktown.occupation_types as tot_occupations
from neighborly.plugins.talktown import business_components
from neighborly.plugins.talktown.personality import (
    BigFivePersonality,
    BigFivePersonalityFactory,
)
from neighborly.plugins.talktown.school import SchoolSystem, Student
from neighborly.simulation import Plugin, Simulation

logger = logging.getLogger(__name__)


class TalkOfTheTownPlugin(Plugin):
    def setup(self, sim: Simulation, **kwargs: Any) -> None:
        sim.world.add_system(SchoolSystem())

        # Register student component for school system
        sim.engine.register_component(Student)

        # Register Personality component
        sim.engine.register_component(
            BigFivePersonality, factory=BigFivePersonalityFactory()
        )

        # Register Business components
        sim.engine.register_component(business_components.ApartmentComplex)
        sim.engine.register_component(business_components.Bakery)
        sim.engine.register_component(business_components.Bank)
        sim.engine.register_component(business_components.Bar)
        sim.engine.register_component(business_components.Barbershop)
        sim.engine.register_component(business_components.BlacksmithShop)
        sim.engine.register_component(business_components.Brewery)
        sim.engine.register_component(business_components.BusDepot)
        sim.engine.register_component(business_components.ButcherShop)
        sim.engine.register_component(business_components.CandyStore)
        sim.engine.register_component(business_components.CarpentryCompany)
        sim.engine.register_component(business_components.Cemetery)
        sim.engine.register_component(business_components.CityHall)
        sim.engine.register_component(business_components.ClothingStore)
        sim.engine.register_component(business_components.CoalMine)
        sim.engine.register_component(business_components.ConstructionFirm)
        sim.engine.register_component(business_components.Dairy)
        sim.engine.register_component(business_components.DaycareCenter)
        sim.engine.register_component(business_components.Deli)
        sim.engine.register_component(business_components.DentistOffice)
        sim.engine.register_component(business_components.DepartmentStore)
        sim.engine.register_component(business_components.Diner)
        sim.engine.register_component(business_components.Distillery)
        sim.engine.register_component(business_components.DrugStore)
        sim.engine.register_component(business_components.FireStation)
        sim.engine.register_component(business_components.Foundry)
        sim.engine.register_component(business_components.FurnitureStore)
        sim.engine.register_component(business_components.GeneralStore)
        sim.engine.register_component(business_components.GroceryStore)
        sim.engine.register_component(business_components.Hospital)
        sim.engine.register_component(business_components.Hotel)
        sim.engine.register_component(business_components.Inn)
        sim.engine.register_component(business_components.InsuranceCompany)
        sim.engine.register_component(business_components.JewelryShop)
        sim.engine.register_component(business_components.LawFirm)
        sim.engine.register_component(business_components.OptometryClinic)
        sim.engine.register_component(business_components.PaintingCompany)
        sim.engine.register_component(business_components.Park)
        sim.engine.register_component(business_components.Pharmacy)
        sim.engine.register_component(business_components.PlasticSurgeryClinic)
        sim.engine.register_component(business_components.PlumbingCompany)
        sim.engine.register_component(business_components.PoliceStation)
        sim.engine.register_component(business_components.Quarry)
        sim.engine.register_component(business_components.RealtyFirm)
        sim.engine.register_component(business_components.Restaurant)
        sim.engine.register_component(business_components.School)
        sim.engine.register_component(business_components.ShoemakerShop)
        sim.engine.register_component(business_components.Supermarket)
        sim.engine.register_component(business_components.TailorShop)
        sim.engine.register_component(business_components.TattooParlor)
        sim.engine.register_component(business_components.Tavern)
        sim.engine.register_component(business_components.TaxiDepot)
        sim.engine.register_component(business_components.University)

        # Register OccupationTypes
        sim.engine.occupation_types.add(tot_occupations.apprentice)
        sim.engine.occupation_types.add(tot_occupations.architect)
        sim.engine.occupation_types.add(tot_occupations.baker)
        sim.engine.occupation_types.add(tot_occupations.banker)
        sim.engine.occupation_types.add(tot_occupations.bank_teller)
        sim.engine.occupation_types.add(tot_occupations.barber)
        sim.engine.occupation_types.add(tot_occupations.barkeeper)
        sim.engine.occupation_types.add(tot_occupations.bartender)
        sim.engine.occupation_types.add(tot_occupations.bottler)
        sim.engine.occupation_types.add(tot_occupations.blacksmith)
        sim.engine.occupation_types.add(tot_occupations.brewer)
        sim.engine.occupation_types.add(tot_occupations.bricklayer)
        sim.engine.occupation_types.add(tot_occupations.builder)
        sim.engine.occupation_types.add(tot_occupations.busboy)
        sim.engine.occupation_types.add(tot_occupations.bus_driver)
        sim.engine.occupation_types.add(tot_occupations.butcher)
        sim.engine.occupation_types.add(tot_occupations.carpenter)
        sim.engine.occupation_types.add(tot_occupations.cashier)
        sim.engine.occupation_types.add(tot_occupations.clothier)
        sim.engine.occupation_types.add(tot_occupations.concierge)
        sim.engine.occupation_types.add(tot_occupations.cook)
        sim.engine.occupation_types.add(tot_occupations.cooper)
        sim.engine.occupation_types.add(tot_occupations.daycare_provider)
        sim.engine.occupation_types.add(tot_occupations.dentist)
        sim.engine.occupation_types.add(tot_occupations.dishwasher)
        sim.engine.occupation_types.add(tot_occupations.distiller)
        sim.engine.occupation_types.add(tot_occupations.doctor)
        sim.engine.occupation_types.add(tot_occupations.dressmaker)
        sim.engine.occupation_types.add(tot_occupations.druggist)
        sim.engine.occupation_types.add(tot_occupations.engineer)
        sim.engine.occupation_types.add(tot_occupations.farmer)
        sim.engine.occupation_types.add(tot_occupations.farmhand)
        sim.engine.occupation_types.add(tot_occupations.fire_chief)
        sim.engine.occupation_types.add(tot_occupations.fire_fighter)
        sim.engine.occupation_types.add(tot_occupations.grocer)
        sim.engine.occupation_types.add(tot_occupations.groundskeeper)
        sim.engine.occupation_types.add(tot_occupations.hotel_maid)
        sim.engine.occupation_types.add(tot_occupations.inn_keeper)
        sim.engine.occupation_types.add(tot_occupations.insurance_agent)
        sim.engine.occupation_types.add(tot_occupations.janitor)
        sim.engine.occupation_types.add(tot_occupations.jeweler)
        sim.engine.occupation_types.add(tot_occupations.joiner)
        sim.engine.occupation_types.add(tot_occupations.laborer)
        sim.engine.occupation_types.add(tot_occupations.landlord)
        sim.engine.occupation_types.add(tot_occupations.lawyer)
        sim.engine.occupation_types.add(tot_occupations.manager)
        sim.engine.occupation_types.add(tot_occupations.miner)
        sim.engine.occupation_types.add(tot_occupations.milkman)
        sim.engine.occupation_types.add(tot_occupations.mayor)
        sim.engine.occupation_types.add(tot_occupations.molder)
        sim.engine.occupation_types.add(tot_occupations.mortician)
        sim.engine.occupation_types.add(tot_occupations.nurse)
        sim.engine.occupation_types.add(tot_occupations.optometrist)
        sim.engine.occupation_types.add(tot_occupations.owner)
        sim.engine.occupation_types.add(tot_occupations.painter)
        sim.engine.occupation_types.add(tot_occupations.pharmacist)
        sim.engine.occupation_types.add(tot_occupations.plasterer)
        sim.engine.occupation_types.add(tot_occupations.plastic_surgeon)
        sim.engine.occupation_types.add(tot_occupations.plumber)
        sim.engine.occupation_types.add(tot_occupations.police_chief)
        sim.engine.occupation_types.add(tot_occupations.police_officer)
        sim.engine.occupation_types.add(tot_occupations.principal)
        sim.engine.occupation_types.add(tot_occupations.professor)
        sim.engine.occupation_types.add(tot_occupations.proprietor)
        sim.engine.occupation_types.add(tot_occupations.puddler)
        sim.engine.occupation_types.add(tot_occupations.quarry_man)
        sim.engine.occupation_types.add(tot_occupations.realtor)
        sim.engine.occupation_types.add(tot_occupations.seamstress)
        sim.engine.occupation_types.add(tot_occupations.secretary)
        sim.engine.occupation_types.add(tot_occupations.stocker)
        sim.engine.occupation_types.add(tot_occupations.shoemaker)
        sim.engine.occupation_types.add(tot_occupations.stonecutter)
        sim.engine.occupation_types.add(tot_occupations.tailor)
        sim.engine.occupation_types.add(tot_occupations.tattoo_artist)
        sim.engine.occupation_types.add(tot_occupations.taxi_driver)
        sim.engine.occupation_types.add(tot_occupations.teacher)
        sim.engine.occupation_types.add(tot_occupations.turner)
        sim.engine.occupation_types.add(tot_occupations.waiter)
        sim.engine.occupation_types.add(tot_occupations.whitewasher)
        sim.engine.occupation_types.add(tot_occupations.woodworker)

        # Register Business Archetypes
        sim.engine.business_archetypes.add(tot_businesses.bakery)
        sim.engine.business_archetypes.add(tot_businesses.bank)
        sim.engine.business_archetypes.add(tot_businesses.bar)
        sim.engine.business_archetypes.add(tot_businesses.barbershop)
        sim.engine.business_archetypes.add(tot_businesses.bus_depot)
        sim.engine.business_archetypes.add(tot_businesses.carpentry_company)
        sim.engine.business_archetypes.add(tot_businesses.cemetery)
        sim.engine.business_archetypes.add(tot_businesses.city_hall)
        sim.engine.business_archetypes.add(tot_businesses.clothing_store)
        sim.engine.business_archetypes.add(tot_businesses.coal_mine)
        sim.engine.business_archetypes.add(tot_businesses.construction_firm)
        sim.engine.business_archetypes.add(tot_businesses.dairy)
        sim.engine.business_archetypes.add(tot_businesses.day_care)
        sim.engine.business_archetypes.add(tot_businesses.deli)
        sim.engine.business_archetypes.add(tot_businesses.dentist_office)
        sim.engine.business_archetypes.add(tot_businesses.department_store)
        sim.engine.business_archetypes.add(tot_businesses.diner)
        sim.engine.business_archetypes.add(tot_businesses.distillery)
        sim.engine.business_archetypes.add(tot_businesses.drug_store)
        sim.engine.business_archetypes.add(tot_businesses.farm)
        sim.engine.business_archetypes.add(tot_businesses.fire_station)
        sim.engine.business_archetypes.add(tot_businesses.foundry)
        sim.engine.business_archetypes.add(tot_businesses.furniture_store)
        sim.engine.business_archetypes.add(tot_businesses.general_store)
        sim.engine.business_archetypes.add(tot_businesses.grocery_store)
        sim.engine.business_archetypes.add(tot_businesses.hardware_store)
        sim.engine.business_archetypes.add(tot_businesses.hospital)
        sim.engine.business_archetypes.add(tot_businesses.hotel)
        sim.engine.business_archetypes.add(tot_businesses.inn)
        sim.engine.business_archetypes.add(tot_businesses.insurance_company)
        sim.engine.business_archetypes.add(tot_businesses.jewelry_shop)
        sim.engine.business_archetypes.add(tot_businesses.law_firm)
        sim.engine.business_archetypes.add(tot_businesses.optometry_clinic)
        sim.engine.business_archetypes.add(tot_businesses.painting_company)
        sim.engine.business_archetypes.add(tot_businesses.park)
        sim.engine.business_archetypes.add(tot_businesses.pharmacy)
        sim.engine.business_archetypes.add(tot_businesses.plastic_surgery_clinic)
        sim.engine.business_archetypes.add(tot_businesses.plumbing_company)
        sim.engine.business_archetypes.add(tot_businesses.police_station)
        sim.engine.business_archetypes.add(tot_businesses.quarry)
        sim.engine.business_archetypes.add(tot_businesses.realty_firm)
        sim.engine.business_archetypes.add(tot_businesses.restaurant)
        sim.engine.business_archetypes.add(tot_businesses.school)
        sim.engine.business_archetypes.add(tot_businesses.shoemaker_shop)
        sim.engine.business_archetypes.add(tot_businesses.supermarket)
        sim.engine.business_archetypes.add(tot_businesses.tailor_shop)
        sim.engine.business_archetypes.add(tot_businesses.tattoo_parlor)
        sim.engine.business_archetypes.add(tot_businesses.tavern)
        sim.engine.business_archetypes.add(tot_businesses.taxi_depot)


def get_plugin() -> Plugin:
    return TalkOfTheTownPlugin()
