chance_of_interaction_extroversion_component_floor = 0.05
chance_of_interaction_extroversion_component_cap = 0.7
chance_of_interaction_openness_component_floor = 0.01
chance_of_interaction_openness_component_cap = 0.7
chance_of_interaction_friendship_component = 0.5
chance_of_interaction_best_friend_component = 0.2
chance_someone_instigates_interaction_with_other_person_floor = 0.05
chance_someone_instigates_interaction_with_other_person_cap = 0.95
